name: Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Front-End image
        run: |
          docker build -t your-dockerhub-username/frontend:latest -f Dockerfile-frontend .
          docker push your-dockerhub-username/frontend:latest

      - name: Push Back-End image
        run: |
          docker build -t your-dockerhub-username/backend:latest -f Dockerfile-backend .
          docker push your-dockerhub-username/backend:latest

      - name: Push Database image
        run: |
          docker build -t your-dockerhub-username/database:latest -f Dockerfile-database .
          docker push your-dockerhub-username/database:latest

  simulate-deploy:
    needs: publish-images
    runs-on: ubuntu-latest

    steps:
      - name: Simulate Deployment
        run: echo "Deploying images to production environment..."